# Generated by Django 4.2.14 on 2024-07-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('full_name', models.CharField(max_length=100)),
                ('profile_title', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='img/')),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
    ]
