# Generated by Django 4.2.14 on 2024-07-30 04:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_educationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('icon', models.ImageField(upload_to='img/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
