# Generated by Django 4.2.14 on 2024-07-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0005_certificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationmodel',
            name='icon',
            field=models.CharField(max_length=200),
        ),
    ]
