# Generated by Django 4.2.14 on 2024-08-03 04:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_alter_certificationmodel_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/img/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
